### ISSUE TITLE
Redis might have been the wrong choice...

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#101]
I wanted to start an issue for this discussion because right now we are using Redis to store historic scrape logs -- those logs are used to determine whether or not a scrape has happened already and should be skipped.

Redis is ephemeral, meaning its data could disappear at any given moment.  Originally my thinking was "well if that happens worst case we scrape things again" but (1) that is an expensive worst case even if it isn't conceptually application breaking and (2) boy does the redis store get big fast!  (local store is 13GB at the time of writing, and that isn't even the bulk of the full CNN scrapes)

Point is: maybe we should use SQL for this; we could potentially use Redis as a faster cache of the SQL data, but there should be a mechanism to re-load history in the event of a store wipe.

**Comment by cguess** [comment]
What exactly are you storing in the Redis database? The results or just the urls and status? Seems like storing the scrapes themselves in Redis is a bit much. If we're looking for key/value we could look at a no-sql database backing ([MongoDb](https://www.mongodb.com/), [Couchbase](https://www.couchbase.com/), etc.), which seems like an actually decent use case for this tech for once.

**Comment by cguess** [comment]
Thinking about this for a second, NoSQL would probably be easiest to go with here, since with Redis I'm guessing you're already using key/value retrieval, so doing so with Mongo or whatever would be more "drop in".

**Comment by reefdog** [comment]
Can we just use Postgres?

1. We already are, so one less thing to setup/maintain/break.
2. A scrapes table with an indexed column of URLs should be very fast since we aren't fetching other columns/relations; if very fast isn't fast enough, we can then wrap Redis or something around it as a cache. (But also that'd be surprising since we're basically recreating the index at that point.)
3. We can store richer amounts of info on each scrape without theoretically affecting the query speed (since the query would only be against the indexed column).
4. Postgres has internal tuning to keep high-demand tables/indices in memory, which is almost certainly more important for performance than what store we use. (In fact, assuming Postgres is smart enough to only load the high-demand index into memory rather than the whole table, then its memory consumption should be way less than Redis' even if/as we store way more info on each row.)

**Comment by slifty** [comment]
Yes!  Implementing the postgres version now.  I'll start by continuing to store the same data I was storing in redis (e.g. scrape outcome / error / etc)
