### ISSUE TITLE
Experiment: Improve CNN feed using ClaimReview

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#103]
Per @markstencel:

> I am still eager to see if using speakers from ClaimReview is a way to improve our CNN feed and effectively screen out CNN personalities. That might be something we can text and check outside of the system you’ve built. (Take the same list of claims that’s used to produce the daily alert and match against ClaimReview.)

**Comment by slifty** [comment]
We met about this last week and talked through the use case behind this experiment.  The primary goal is to make sure fact checkers are regularly seeing relevant fact checks in the emails (the thinking is that the more "noise" appears in the list the less it will be used)

The theory behind this experiment is that by restricting claims to previously-fact-checked figures we will increase the saturation of those "good" claims in the list.

Some concerns raised about this approach was:

1. Fuzzy name matching (Dan vs Daniel)
2. Rising figures / folks who are important but haven't yet been checked

We looked at potentially leveraging something like DBPedia to help address both issues.

That said, the first experiment / most simple experiment is to just use a static list from anywhere and see what the result looks like.  This can be done entirely locally as a first step.

**Comment by slifty** [comment]
Emil ran an experiment here (I'm posting the results on her behalf since she is in the middle of finals week).  I don't think we're going to commit the code for the experiment since it was done as a one-off and we won't be merging it directly, but the takeaway is that it resulted in success.

There appeared to be enough claims to fill a standard newsletter even without fuzzy matching.  We talked about whether to create a new section of the newsletter for these pre-identified high profile speakers, but decided that for the immediate future we should just create logic along the lines of: "Select claims from known speakers; if there aren't enough, fill the rest with other claims."

I'm going to close this issue and open a new one reflecting the feature addition that will come out of this.
