### ISSUE TITLE
Transcript errors generate log noise

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#115]
We (correctly) [throw an error when encountering an unfamiliar transcript format](https://github.com/TechAndCheck/tech-and-check-alerts/blob/e1ac344c6281b1a367eaa9ed01c6e8a16efb2f66/src/server/workers/scrapers/CnnTranscriptStatementScraper.js#L37), which eventually gets [caught and logged by AbstractScraper](https://github.com/TechAndCheck/tech-and-check-alerts/blob/e1ac344c6281b1a367eaa9ed01c6e8a16efb2f66/src/server/workers/scrapers/AbstractScraper.js#L146).

However, when this fails, the `run()` function doesn't return anything. This throws off the job processors that actually run the scrapers, because they are written to act immediately on the results of `run()`. [Example](https://github.com/TechAndCheck/tech-and-check-alerts/blob/e1ac344c6281b1a367eaa9ed01c6e8a16efb2f66/src/server/queues/cnnTranscriptStatementScraperQueue/cnnTranscriptStatementScraperJobProcessor.js#L15-L16):

```js
const statements = await scraper.run()
statements.forEach(detectClaims)
```

That code generates an error because `scraper.run()` returns undefined, so `forEach` can't be run on it.

We should either (1) insist that every time we call `run()` we provide a fallback value, ala `const statements = await scraper.run() || []`, or (2) define an abstract method on `AbstractScraper()`, such as `getNullScrapeValue()`, that must be overridden by each implementation, that returns a scraper-specific null value of the correct type. E.g.:

```js
class AbstractStatementScraper {
  // ... existing stuff

  getNullScrapeValue = () => []
}
```

And then modify `AbstractrScraper#run()` to return that during the catch(), e.g.:

```js
async run() {
  return rp(this.scrapeUrl)
    .then((responseString) => {
      // … existing stuff
    })
    .catch((err) => {
      // … existing stuff
      return this.getNullScrapeValue()
    })
}
```

I think (2) is the right way to go.

**Comment by slifty** [comment]
Hmm -- I'm having trouble thinking of a time when we would ever want a null value to return anything but [].  While I like the OOP allure of more abstract methods, I have a strong feeling it will never NOT be a method that just returns `[]` <-- let me know if that isn't the case.

The issue here I'm trying to grapple with is the idea of the right way to error handle async stuff.

I believe, in theory we should NEVER have an await that is not wrapped in a try / catch, since await can always error.

So: I'm less worried about abstracting the null case return value (I think we can always return []) than I am about deciding the right place to catch the error. 

Is `run` the right place to error catch?  Yeah probably.  But we should probably also catch at the worker since worker should never assume a promise is guaranteed to resolve without error.

**Comment by reefdog** [comment]
> I have a strong feeling it will never NOT be a method that just returns `[]`

This is what I wasn't sure about. I looked at all the scraper and crawler examples, and I think they all return arrays, but didn't know if that was just circumstantial.

Really I'm just trying to get away from undocumented implementation requirements (which my original Slack suggestion of option (1) above is). Either we centralize it at `run()` or use an abstract method, or… something.

**Comment by slifty** [comment]
It's definitely documented to return an array already (or should be); and it makes sense that the array would be empty if the scraper returned no arrays.

I think we should definitely do what you suggest around run() and have run return [] on error (no abstract method needed).  (We should consider a logger.info or logger.debug in run announcing that it is returning a fallback value.)

I think we should also consider wrapping the await in the worker with a try catch regardless since that is good practice.

**Comment by slifty** [comment]
Sorry -- storeScrapeResult is what is documented as returning an array (that's the intended return endpoint though -- ugh, how do you document "this returns a promise that returns an array")

The world was not meant for promises.

**Comment by reefdog** [comment]
> I think we should also consider wrapping the await in the worker with a try catch regardless since that is good practice.

That's sensible, and we should do it. Opened as #119.
