### ISSUE TITLE
Discuss adding metric monitoring

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/tech-and-check-alerts#158]
Since we're running our own server we should probably have some monitoring with alerts set up. There's a bunch of paid and free systems for this.

For FactStream we use Heroku's native monitoring and [New Relic](https://newrelic.com/)

For plain AWS instances there's more options, including hosting our own. A few options:
- [Zabbix](https://www.zabbix.com/) This is what I've used before, but recently been waved away from simply for ease of use purposes. Still an option
- [Prometheus](https://prometheus.io/) Which is a very popular open source as well.

Both of these we have to host the central server ourselves, but that's easy.

With this we'll be able to monitor CPU, RAM, swap, etc. without having to log into the system. It can then alert us if something goes wrong.

**Comment by cguess** [comment]
Bull already supports Prometheus https://github.com/UpHabit/bull_exporter

**Comment by cguess** [comment]
I've set up a Prometheus server with Grafana as a frontend, limited to just my IP at the moment. I'll figure out getting it to measure a everything this weekend.

**Comment by slifty** [comment]
Chris and I just had another conversation about this and the plan is to continue running with Prometheus.  The rationalle is because (1) it is FOSS, which means that after the learning curve and setup it will not have explicit ongoing costs aside from hosting (2) it is the most flexible option.

I'll be spending some time this week getting up to speed on Prometheus and figuring out what has to be done to finally address #35

**Comment by slifty** [comment]
Technically this has been discussed; there is a fair amount of design work around metrics (naming, scope, etc) to do this with full fidelity.

Some resources I'm using to traverse the learning curve:

* [This excellent best practices handbook](https://prometheus.io/docs/practices/naming/).  Note that there are additional sections after that link.
* [This philosophy](https://docs.google.com/document/d/199PqyG3UsyXlwieHaqbGiWVa8eMWi8zzAn0YfcApr8Q/edit) on alerts.
* [A guide](https://prometheus.io/docs/guides/node-exporter/) for setting up system monitoring.

At this point I think that the task scoped by this issue is complete; there are some spinoff issues around the metrics design, Node Exporter setup, and application-level Prometheus integration that I will create now and relate them to #35.
