### ISSUE TITLE
Fix sender display in Outlook webmail

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/tech-and-check-alerts#166]
Sender looks like this in Outlook webmail:

```
From: alerts=factstream.co@alerts.factstream.co <alerts=factstream.co@alerts.factstream.co> on behalf of Tech & Check Alerts <alerts@factstream.co>
Sent: Monday, August 19, 2019 1:31 PM
To: Mark Stencel <mark.stencel@duke.edu>
Subject: Tech & Check Alerts
```

@markstencel is the original reporter. I don't have Outlook to reproduce. This issue does not appear in Gmail in Chrome or in iOS Mail app.

**Comment by reefdog** [comment]
For those who can login to Mailgun, I've opened a ticket with them about this: https://app.mailgun.com/app/support/1030534

**Comment by reefdog** [comment]
Ah, Mailgun has a support doc about this: https://help.mailgun.com/hc/en-us/articles/360012491394-Why-Do-I-See-On-Behalf-Of-in-My-Email-

Essentially, this is happening because our confirmed domain is `alerts.factstream.co` but we're sending from `factstream.co`. They suggest these be in alignment.

Should we just start sending from `alerts@alerts.factstream.co` instead?

**Comment by ericaryan** [comment]
Can we not confirm factstream.co as our domain for sending?

**Comment by reefdog** [comment]
I would love that, but I honestly don't understand Mailgun's model well enough to understand if they require us to do anything to that domain (like point MX records there) that are non-starters.

@cguess Do you know? _Can_ we use `factstream.co` as our confirmed domain w/in Mailgun instead of `alerts.factstream.co`? I would think they'd only require MX records pointed there if we wanted it to receive mail, which we don't. Everything else should be handleable through CNAMEs and TXT records or whatever, right?

**Comment by cguess** [comment]
I can check it.

**Comment by cguess** [comment]
Adding factstream.co as a domain now.

**Comment by reefdog** [comment]
@cguess How's the DNS stuff going? Mailgun's still saying the records aren't pointed. Anything I can do to help sort it out?
