### ISSUE TITLE
Diagram technical architecture

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#2]
Using what we know about the project, create a technical architecture diagram we can use for  gap analysis of the [existing codebase](https://github.com/oneroyalace/Tech-Check-Alerts) and future development.

**Comment by reefdog** [comment]
Quick v1.0 version of the technical architecture diagram. This will get more detail.

<img width="583" alt="diagram" src="https://user-images.githubusercontent.com/4731/56840787-1bd28f80-684f-11e9-8ad6-83b2e7b67eb6.png">

**Comment by slifty** [comment]
Some other nodes to add:

1) Claimbuster, which is a third party API.
2) We may want to wrap the DB in an API layer, rather than having multiple applications work directly with the same database.

**Comment by slifty** [comment]
Capturing the outcome and deliberations of our discussion this morning!

## The Approaches
We were trying to choose between two approaches:

### Approach 1: Monolithic application

The first option would be to put the subscription service in the same project as the scrapers.  This would have the benefits of:

1. Simpler architecture; easier to maintain and set up.  You don't have multiple CI and automated deployment processes going on for each project.
2. Common database and model / schema files.  Both projects that interact with the database would be able to leverage the same models.  Avoiding redundancy

### Approach 2: Distinct services

Decoupling the code that generates content from the code that uses the content by putting them in separate projects and deploying them separately.

This would mean breaking the core claim database into its own service that is used by both pieces of the application.  The side applications might have their own databases to manage their parts of the world (e.g. email lists)

This would have the benefit of:

1. Ability to scale each piece of the project separately.
2. More flexibility down the line for creating new types of "clients" that use this data.

## The Decision

Since this project isn't too complex right now, we're going with Approach #1 and having a single project that handles everything under one roof.  This does not prevent us from moving into a more complex architecture in future if scraping starts to become a much more involved process / the data starts becoming too great, or if we start building out more robust subscription management and consumer interfaces.

This also doesn't prevent us from incorporating talking point tracker data at some point in the future (likely by creating a scraper module that scrapes TPT)

@reefdog is going to update the diagram to reflect these decisions!

**Comment by reefdog** [comment]
Here's largely what we discussed:

1. **Node.js scrapers** fetch data from target sites
2. **Node.js parsers** pass data to an external ClaimBuster API and potentially additional to additional services (like a Python spaCy service we spin up). Technically, this will be coupled to the scraper, but I'm representing it separately for clarity.
3. **Postgres DB** that receives claim data (and, for now, also stores the subscription data).
4. **Node.js subscription manager** that mostly **composes the emails** and fires them off to a **delivery service** (like Mailgun or Amazon SES), but could also expose a **user portal** for **subscriber self-management** (subscribing, unsubscribing, changing email address, changing delivery options).

To start, all these components will be developed in the same repo, directly coupled, and served from the same instance. In future, we could abstract each out to its own machine/service as needed.

![tca-diagram](https://user-images.githubusercontent.com/4731/57105127-9d16a000-6cef-11e9-82a0-ac1ea781f369.png)
