### ISSUE TITLE
Use preferred Twitter display names

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/tech-and-check-alerts#249]
@markstencel noticed that sometimes we are possibly using Twitter handles instead of the desired display names. Filing this as a placeholder for checking this issue. @markstencel Please update with examples if you have them because I haven't been tracking this!

**Comment by reefdog** [comment]
Confirmed, for some reason we're using the scraped name and not the stored name. Looking into it!

**Comment by reefdog** [comment]
Well, that'd be because we never configured it do use the preferred name. 🤦‍♂

@slifty I'm thinking about whether we should insert the preferred name at scrape time or newsletter composition time. On the one hand, doing it at scrape time essentially pollutes the idea of purely "scraping". On the other hand, this isn't _too_ far off from the transformations and filtering we do on speaker names for CNN already. Thoughts?

**Comment by slifty** [comment]
Scrape time seems appropriate -- I agree that this is essentially the same as NormalizeSpeakerNames.
