### ISSUE TITLE
Make major platform decisions (languages, environments)

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#4]
After determining the technical architecture (#2), we should decide:

- What languages should each component be written in?
- What hosting services/environments are appropriate for each component?
- What complexity of best development practices (CI testing, automated deployment, production redundancy, etc.) are worthwhile?

**Comment by slifty** [comment]
Some current thinking on these issues

## Language
Python or Node.

Python is what the current application is written in, so there would be value there.  Python also has the most robust NLP libraries and so that is value added.  It's unclear if there is a preference within tech and check at large for python.

Node is what Dan and Justin personally prefer these days, and any NLP functionality may be best separated as a microservice regardless.  We're likely going to want to build any future frontend using react (which means node would likely be used regardless)


## Hosting services
Currently hosted on a digital ocean droplet; we're going to want to use whatever the rest of the tech and check services use.

## CI etc
For what it's worth: I think it will definitely be worth setting up CI and automated deployment once we get our ducks in a row on the first two items.  Production redundancy probably not so much.

**Comment by slifty** [comment]
Some thoughts on this now that we've fleshed out #2 a bit more.

1. We're going to do this in Node.js, using a similar stack to the one we used for Talking Point Tracker.
2. This will be hosted on AWS (medium instance is fine), with automated deployment from `master`
3. Lets just use [Travis](https://travis-ci.org/)!

**Comment by slifty** [comment]
Broke some of the actions stemming from these decisions out into their own issues (#9, #8, #10)
