### ISSUE TITLE
Add memory to our scrapers

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#66]
We need a way to prevent the scrape of the same pages twice.  This behavior won't be the same for each type of scraper (for instance we want to crawl the CNN transcript portal every day, but we never want to scrape the same transcript more than once), but the functionality should be part of the abstract classes and configured at the implementation level.

## Where should we store

We could either...

1. Use SQL to cache the list of URLs that have been scraped (ID, URL, scraperClass, dateScraped).

2. Use the file system; write to a {urlHash}.txt file upon successful scrape, and maybe even store the results of the scrape in the file.

3. Use Redis instead of a filesystem.

This feels like a non-optimal use for SQL, but since we're looking at thousands of scrapes (not millions or billions) anything could work.  I'm leaning towards Redis since we already use Redis for the scraping process and it has most benefits of the filesystem but is more engineered / can scale as needed.

## Allowing configuration

Two approaches to configuration:

1. Have the default run() behavior check the database first and reject the scrape if it is a duplicate; provide the ability to force the run by passing in run(true)

2. Create the ability to set a repetition frequency in the overriding class (similar to the way we do schedules)

**Comment by reefdog** [comment]
Some thoughts:

1. Read performance is most important. We don't care how quickly it writes (within reason).
2. Not that I'm otherwise arguing for SQL over Redis, but "since we're looking at thousands of scrapes (not millions or billions) anything could work" implies SQL is more appropriate at K-scale than M/B-scale. Why is that? MySQL/PostgreSQL are… rather proven at those scales.
3. This is basically a flat denylist: we configure which types of URLs, once scraped, shouldn't be scraped again unless forced. Add those to the denylist. Upon run, filter the scrapelist by the denylist. If we want to _also_ keep a record of every URL scraped (regardless of whether it can be re-run) and when, that's fine too, but without a clear use for that data right now we should make sure it doesn't take precedence over the immediate need. (But of course, if it's a little more work for a lot of long-term historical record we want to keep, now's the best time.)

**Comment by slifty** [comment]
Re #2: I could be totally off base!  My understanding is that postgres is just a bit slower than redis for this kind of simple lookup, which doesn't matter at K scale but could start to impact performance at M / B.  Some of this is because SQL has a lot more guarantees around consistency and not losing data.  We don't really care about those things for this use case because worst case we just scrape something an extra time.

I've also had SQL tables start to fall apart after too many rows but that could just be because I was using MySQL's InnoDB (is that still a thing, I don't even know).

Re #3: It feels similarly simple to just keep a log of each time a scrape happens as to have a denylist, so I'm leaning towards the extra bit of potential information.  The logic would be "check if the URL has a hash, check the most recent date in the hash, invoke any logic around things getting stale"

**Comment by reefdog** [comment]
I think you're right that Redis is gonna be faster than My/PostgreSQL for our uses.

I think the most important thing for performance is that we (1) can keep it in memory, and (2) have performant queries (through sensible tuning and indexing). Also, this is totally sniff test (and premature optimization until we know the latency on each query), but checking a list of scrape URLs against the denylist in one operation rather than one-query-per-URL seems like a nice optimization to consider, which would basically mean checking the list of URLs _before_ splitting them off to the queue rather than during their processing. Just something to consider when building.

**Comment by slifty** [comment]
I ended up going the Redis path.

New question:  What should count as a "scrape" having happened.  In other words, what should the scraper "skip" logic be.

Options are:

* Skip any page that has been successfully scraped
* Skip any page where a scrape has ever been attempted
* Skip any page that has been successfully scraped OR has been attempted in the past X time period

The challenge is that there are some pages that will return a 404.  In those cases we wouldn't want to re-attempt them in future.  On the other hand, there are some pages where parsing might break, and we might want to re-run those.

I'm leaning towards skipping any page where an ATTEMPT has been made, but maybe creating an issue for some day making it easy to flush the relevant logs for a given URL so we can easily re-scrape.

Thoughts?

**Comment by reefdog** [comment]
We wouldn't want to blocklist a whole bunch of URLs just because of a temporary outage on their end, so I don't think an automatic skip of anything attempted it quite fine enough.

I think we're gonna have to store an "attempt" count and a "success" count/boolean, so we can say "skip if successful or attempted X times". Periodically we can dump everything that's maxed out its attempts with no success, and do a special run of them just to see if any have sprung to life.

**Comment by slifty** [comment]
Great points.  We get some degree of configuration about retries through Bull (the queue manager) directly, so I would like to avoid building our own retry tracking system if possible.

I'm a also bit wary of trying to get too smart with our retry before we know what kinds of problems we'll face.  I would rather lean towards having the "retry" stuff start off a bit more manual so we can gather data on failure modes.

One note that in the event of a known outage event we would easily be able to have a super simple script that wipes all scrape records that happened in {time range}.

**Comment by reefdog** [comment]
Sounds good to me!

**Comment by reefdog** [comment]
This was moved to Done, but hasn't been closed. Should we close it, @slifty?

**Comment by slifty** [comment]
Lets close it!
